# Pytorch 小练习

In [21]:
import torch
import torch.nn.functional as F
import torch.nn as nn
import numpy as np

## 实现softmax函数

In [ ]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用torch自带的softmax函数'''
    ##########
    exp = x.exp()
    return exp/exp.sum(dim=-1,keepdim=True)

test_data = torch.randn((10,5))
(softmax(test_data).numpy() - F.softmax(test_data, dim=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [20]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    ##########
    return 1/(1+(-x).exp())

test_data = torch.rand((10,5))
(sigmoid(test_data).numpy() - F.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [39]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用torch自带的softmax_cross_entropy函数'''
    ##########
    return (-label*torch.log(x)).sum(-1).mean()

test_data = torch.rand((10, 5))
prob = F.softmax(test_data,dim=-1)
label = torch.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

# F.cross_entropy接受的是logits
((F.cross_entropy(test_data,label)
  - softmax_ce(prob, label))**2 < 0.0001).numpy()

array(True)

## 实现 sigmoid 交叉熵loss函数

In [ ]:
def sigmoid_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用torch自带的softmax_cross_entropy函数'''
    ##########
    return (-label*torch.log(x)-(1-label)*torch.log(1-x)).mean()

test_data = torch.rand(10)
prob = F.sigmoid(test_data)
label = torch.randint(0, 2, (10,)).to(torch.float)
print (label)

((F.binary_cross_entropy(prob,label)- sigmoid_ce(prob, label))**2 < 0.0001).numpy()



tensor([1., 1., 1., 1., 1., 0., 1., 0., 0., 1.])


array(True)

: 